ALTER TABLE ruches ADD COLUMN IF NOT EXISTS has_corps BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ruches ADD COLUMN IF NOT EXISTS has_hausse BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ruches ADD COLUMN IF NOT EXISTS has_grille_a_reine BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ruches ADD COLUMN IF NOT EXISTS has_nourrisseur BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ruches ADD COLUMN IF NOT EXISTS has_toit BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ruches ADD COLUMN IF NOT EXISTS has_plancher BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE visites_ruche ADD COLUMN IF NOT EXISTS corps_present BOOLEAN;
ALTER TABLE visites_ruche ADD COLUMN IF NOT EXISTS hausse_presente BOOLEAN;
ALTER TABLE visites_ruche ADD COLUMN IF NOT EXISTS grille_a_reine_presente BOOLEAN;
ALTER TABLE visites_ruche ADD COLUMN IF NOT EXISTS nourrisseur_present BOOLEAN;
ALTER TABLE visites_ruche ADD COLUMN IF NOT EXISTS toit_present BOOLEAN;
ALTER TABLE visites_ruche ADD COLUMN IF NOT EXISTS plancher_present BOOLEAN;
